
package br.com.project.view;

import br.com.project.controller.GerarRelatorio;
import com.github.lgooddatepicker.optionalusertools.CalendarListener;
import com.github.lgooddatepicker.zinternaltools.CalendarSelectionEvent;
import com.github.lgooddatepicker.zinternaltools.YearMonthChangeEvent;
import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author Venicio
 */
//todo colocar os dados da data na impressao do documento em pdf
public class TelaRelatorioOrdens extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorioOrdens
     */
    com.github.lgooddatepicker.components.CalendarPanel calendario =
            new com.github.lgooddatepicker.components.CalendarPanel();

    private JTextField camposelecionado; //recebe a informação de qual campo foi selecionado, atraves do EVt click do mouse gerado!

    public TelaRelatorioOrdens() {
        initComponents();


        // Configura o layout do painel e adiciona o calendário
        PainelCalendario.setLayout(new BorderLayout());
        PainelCalendario.add(calendario, BorderLayout.CENTER);

        // Atualiza o painel
        PainelCalendario.revalidate();
        PainelCalendario.repaint();

        calendario.addCalendarListener(new CalendarListener() {
            //metodo onde captura a data clicada e é passada para o campo selecionado "DE" e "ATÉ";
            @Override
            public void selectedDateChanged(CalendarSelectionEvent calendarSelectionEvent) {
                if (calendarSelectionEvent.getNewDate() != null && camposelecionado != null){
                    LocalDate dataF = calendarSelectionEvent.getNewDate();

                    DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    camposelecionado.setText(dataF.format(formatador));
                }
            }

            @Override
            public void yearMonthChanged(YearMonthChangeEvent yearMonthChangeEvent) {

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbInicioData = new javax.swing.JLabel();
        LbFinalData = new javax.swing.JLabel();
        CampoInicioData1 = new javax.swing.JTextField();
        CampoFinalData = new javax.swing.JTextField();
        PainelCalendario = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Relatorio de Ordens de Serviços");

        LbInicioData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbInicioData.setText("DE:");

        LbFinalData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbFinalData.setText("ATÉ:");

        CampoInicioData1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoInicioData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoInicioData1MouseClicked(evt);
            }
        });
        CampoInicioData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoInicioData1ActionPerformed(evt);
            }
        });

        CampoFinalData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CampoFinalData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoFinalDataMouseClicked(evt);
            }
        });
        CampoFinalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFinalDataActionPerformed(evt);
            }
        });

        PainelCalendario.setBackground(new java.awt.Color(204, 204, 204));
        PainelCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelCalendarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelCalendarioLayout = new javax.swing.GroupLayout(PainelCalendario);
        PainelCalendario.setLayout(PainelCalendarioLayout);
        PainelCalendarioLayout.setHorizontalGroup(
                PainelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 684, Short.MAX_VALUE)
        );
        PainelCalendarioLayout.setVerticalGroup(
                PainelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("GERAR RELATÓRIO");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);

                GerarRelatorio.GerarRelatorio("/relatorios/Ordens.jrxml" , "C:\\Users\\Venicio\\Desktop\\RELATORIOos\\Relatorio_de_Serviços.pdf");
            }

        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LbInicioData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CampoInicioData1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LbFinalData))
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoFinalData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PainelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LbInicioData)
                                        .addComponent(LbFinalData)
                                        .addComponent(CampoInicioData1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CampoFinalData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jButton1)
                                .addContainerGap(467, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PainelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        // Cria o componente de calendário do LGoodDatePicker

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoInicioData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoInicioData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoInicioData1ActionPerformed

    private void CampoFinalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFinalDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFinalDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PainelCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelCalendarioMouseClicked

    }//GEN-LAST:event_PainelCalendarioMouseClicked

    private void CampoInicioData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoInicioData1MouseClicked
        camposelecionado = CampoInicioData1;
    }//GEN-LAST:event_CampoInicioData1MouseClicked

    private void CampoFinalDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoFinalDataMouseClicked
        camposelecionado = CampoFinalData;
    }//GEN-LAST:event_CampoFinalDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoFinalData;
    private javax.swing.JTextField CampoInicioData1;
    private javax.swing.JLabel LbFinalData;
    private javax.swing.JLabel LbInicioData;
    private javax.swing.JPanel PainelCalendario;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
