/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.project.view;

import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
/**
 *
 * @author venic
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();
    }

    //esse metodo serve para colocar o nome do usuario logado
    public void TelaPrincipal2(String UsuarioLogado) {//recebo o parametro do Usuario logado da tela de login.
        InfoUsuLogado.setText(UsuarioLogado);//seta o parametro recebido para oque quero mostrar no JFrame.

    }

    public void MudarNOmesLB() {
        DataHora.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JToolBar();
        Topico = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DataHora = new javax.swing.JLabel();
        InfoUsuLogado = new javax.swing.JLabel();
        CapaTela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BarCadastro = new javax.swing.JMenu();
        MenuCadastroCliente = new javax.swing.JMenuItem();
        CadastrarAdm = new javax.swing.JMenuItem();
        CadastrarOs = new javax.swing.JMenuItem();
        BarRelatorio = new javax.swing.JMenu();
        MenuServiços = new javax.swing.JMenuItem();
        BarAjuda = new javax.swing.JMenu();
        BarOpcoes = new javax.swing.JMenu();
        MenuLogout = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Desktop.setBackground(new java.awt.Color(153, 153, 153));
        Desktop.setRollover(true);

        Topico.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Topico.setText("USUÁRIO");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DataHora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DataHora.setText("jLabel2");

        InfoUsuLogado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        InfoUsuLogado.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InfoUsuLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(InfoUsuLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        CapaTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ordem-de-servico.png"))); // NOI18N
        CapaTela.setText("jLabel2");

        BarCadastro.setText("Cadastro");
        BarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarCadastroActionPerformed(evt);
            }
        });

        MenuCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuCadastroCliente.setText("Cadastrar Cliente");
        MenuCadastroCliente.setEnabled(false);
        MenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroClienteActionPerformed(evt);
            }
        });
        BarCadastro.add(MenuCadastroCliente);

        CadastrarAdm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastrarAdm.setText("CadastrarAdmin");
        CadastrarAdm.setEnabled(false);
        CadastrarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAdmActionPerformed(evt);
            }
        });
        BarCadastro.add(CadastrarAdm);

        CadastrarOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastrarOs.setText("OS");
        CadastrarOs.setEnabled(false);
        CadastrarOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarOsActionPerformed(evt);
            }
        });
        BarCadastro.add(CadastrarOs);

        jMenuBar1.add(BarCadastro);

        BarRelatorio.setText("Relatório");

        MenuServiços.setText("Serviços");
        BarRelatorio.add(MenuServiços);

        jMenuBar1.add(BarRelatorio);

        BarAjuda.setText("Ajuda");
        jMenuBar1.add(BarAjuda);

        BarOpcoes.setText("Opções");

        MenuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuLogout.setText("Logout");
        MenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogoutActionPerformed(evt);
            }
        });
        BarOpcoes.add(MenuLogout);

        MenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        BarOpcoes.add(MenuSair);

        jMenuBar1.add(BarOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(Topico, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(CapaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Topico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CapaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_MenuSairActionPerformed

    private void formWindowActivated(WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("EEEE, dd 'de' MMMM \n'de' yyyy HH:mm:ss", new Locale("pt", "BR"));
        DataHora.setText(formato.format(data));


    }//GEN-LAST:event_formWindowActivated

    private void BarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarCadastroActionPerformed

    }//GEN-LAST:event_BarCadastroActionPerformed

    private void MenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroClienteActionPerformed
        TelaCadastroCliente iniciar = new TelaCadastroCliente();
        iniciar.setVisible(true);
        Desktop.add(iniciar);
    }//GEN-LAST:event_MenuCadastroClienteActionPerformed

    private void MenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogoutActionPerformed
        TelaLogin IniciarLogin = new TelaLogin();
        IniciarLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuLogoutActionPerformed

    private void CadastrarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAdmActionPerformed
        TelaCadastroAdmin iniciar = new TelaCadastroAdmin();
        iniciar.setVisible(true);
        Desktop.add(iniciar);
    }//GEN-LAST:event_CadastrarAdmActionPerformed

    private void CadastrarOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarOsActionPerformed
        TelaGerarOs iniciar = new TelaGerarOs();
        iniciar.setVisible(true);
        Desktop.add(iniciar);
    }//GEN-LAST:event_CadastrarOsActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BarAjuda;
    private javax.swing.JMenu BarCadastro;
    private javax.swing.JMenu BarOpcoes;
    private javax.swing.JMenu BarRelatorio;
    public static javax.swing.JMenuItem CadastrarAdm;
    public static javax.swing.JMenuItem CadastrarOs;
    private javax.swing.JLabel CapaTela;
    private javax.swing.JLabel DataHora;
    private javax.swing.JToolBar Desktop;
    private javax.swing.JLabel InfoUsuLogado;
    public static javax.swing.JMenuItem MenuCadastroCliente;
    private javax.swing.JMenuItem MenuLogout;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JMenuItem MenuServiços;
    private javax.swing.JLabel Topico;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
