/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.project.view;

import br.com.project.controller.ConsultarOs;
import br.com.project.controller.ExcluirOs;
import br.com.project.domain.OrdensDeServico;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Venicio
 */
public class TelaPesquisarOS extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPesquisarOS.class.getName());
    String IdOs = "";
    TelaEditarOS iniciar = new TelaEditarOS();

    public TelaPesquisarOS() {


        initComponents();
        CampoPesquisaOS.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesquisarOs();
            }
        });
    }


    private void PesquisarOs() {
        ConsultarOs consulta = new ConsultarOs();

        List<OrdensDeServico> List = consulta.Consulta(CampoPesquisaOS);

        DefaultTableModel model = new DefaultTableModel(new Object[]{"NºOS", "DATA", "EQUIPAMENTO", "DEFEITO", "SERVIÇO", "CLIENTE", "TEC.RESPONSAVEL", "TIPO", "STATUS", "VALOR"}, 0);
        for (OrdensDeServico OS : List) {
            model.addRow(new Object[]{
                    OS.getOs(),
                    OS.getData_os(),
                    OS.getEquipamento(),
                    OS.getDefeito(),
                    OS.getServico(),
                    OS.getCliente().getNome(),
                    OS.getTecnico(),
                    OS.getTipo(),
                    OS.getStatus(),
                    OS.getValor(),
            });
        }
        TabelaPesquisarOS.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPesquisarOS = new javax.swing.JTable();
        CampoPesquisaOS = new javax.swing.JTextField();
        IconePesquisa = new javax.swing.JLabel();
        IconeDuvida = new javax.swing.JLabel();
        BtImprimirOS = new javax.swing.JButton();
        BtEditarOS1 = new javax.swing.JButton();
        BtExcluirOS1 = new javax.swing.JButton();
        LbPegaIdOS = new javax.swing.JLabel();
        LbOsSelecionada = new javax.swing.JLabel();
        CampoOsSelecionada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PesquisarOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        TabelaPesquisarOS.setBackground(new java.awt.Color(204, 204, 204));
        TabelaPesquisarOS.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null}
                },
                new String[]{
                        "NºOS", "DATA", "EQUIPAMENTO", "DEFEITO", "SERVIÇO", "CLIENTE", "TEC.RESPONSAVEL", "TIPO", "STATUS", "VALOR"
                }
        ));
        TabelaPesquisarOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPesquisarOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaPesquisarOS);

        CampoPesquisaOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CampoPesquisaOSMouseEntered(evt);
            }
        });
        CampoPesquisaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaOSActionPerformed(evt);
            }
        });

        IconePesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-pesquisar-67.png"))); // NOI18N

        IconeDuvida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pergunta-para-fazer-login-em-circulos (1).png"))); // NOI18N
        IconeDuvida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconeDuvidaMouseEntered(evt);
            }
        });

        BtImprimirOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/impressora (1).png"))); // NOI18N
        BtImprimirOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImprimirOSActionPerformed(evt);
            }
        });

        BtEditarOS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editar-arquivo.png"))); // NOI18N
        BtEditarOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarOS1ActionPerformed(evt);
            }
        });

        BtExcluirOS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir-arquivo.png"))); // NOI18N
        BtExcluirOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirOS1ActionPerformed(evt);
            }
        });

        LbOsSelecionada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LbOsSelecionada.setText("O.S SELECIONADA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1510, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(IconePesquisa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CampoPesquisaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(IconeDuvida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(BtEditarOS1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BtExcluirOS1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BtImprimirOS)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(560, 560, 560)
                                                                .addComponent(LbPegaIdOS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(CampoOsSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(LbOsSelecionada, javax.swing.GroupLayout.Alignment.LEADING))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(IconeDuvida, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(IconePesquisa))
                                        .addComponent(CampoPesquisaOS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BtExcluirOS1)
                                                        .addComponent(BtEditarOS1)
                                                        .addComponent(BtImprimirOS)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(LbOsSelecionada)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(CampoOsSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(32, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LbPegaIdOS)
                                                .addGap(59, 59, 59))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPesquisaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaOSActionPerformed

    private void CampoPesquisaOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoPesquisaOSMouseEntered

    }//GEN-LAST:event_CampoPesquisaOSMouseEntered

    private void IconeDuvidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconeDuvidaMouseEntered
        JOptionPane pane = new JOptionPane(
                "Insira o ID do cliente para consultar a ordem de serviço!",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Cria um JDialog com base no JOptionPane
        JDialog dialog = pane.createDialog(null, "Dica");

        // Mostra o diálogo
        dialog.setModal(false); // deixa não-bloqueante
        dialog.setVisible(true);

        // Cria uma thread que fecha o diálogo após 2 segundos
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 2 segundos
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            dialog.dispose(); // fecha a janela
        }).start();
    }//GEN-LAST:event_IconeDuvidaMouseEntered

    private void BtImprimirOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImprimirOSActionPerformed
        if (CampoOsSelecionada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione uma O.S primeiro!");
            return;
        }


    }//GEN-LAST:event_BtImprimirOSActionPerformed

    private void BtEditarOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarOS1ActionPerformed
        iniciar.setVisible(true);
        iniciar.DadosOS(this.IdOs);
    }//GEN-LAST:event_BtEditarOS1ActionPerformed

    private void BtExcluirOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirOS1ActionPerformed
        ExcluirOs Excluir = new ExcluirOs();
        OrdensDeServico OS = Excluir.ExcluirOs(CampoOsSelecionada);
    }//GEN-LAST:event_BtExcluirOS1ActionPerformed

    private void TabelaPesquisarOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPesquisarOSMouseClicked
        int linha = TabelaPesquisarOS.getSelectedRow();

        this.IdOs = TabelaPesquisarOS.getValueAt(linha, 0).toString();
        CampoOsSelecionada.setText(IdOs);
    }//GEN-LAST:event_TabelaPesquisarOSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPesquisarOS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEditarOS1;
    private javax.swing.JButton BtExcluirOS1;
    private javax.swing.JButton BtImprimirOS;
    private javax.swing.JTextField CampoOsSelecionada;
    private javax.swing.JTextField CampoPesquisaOS;
    private javax.swing.JLabel IconeDuvida;
    private javax.swing.JLabel IconePesquisa;
    private javax.swing.JLabel LbOsSelecionada;
    private javax.swing.JLabel LbPegaIdOS;
    private javax.swing.JTable TabelaPesquisarOS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
