/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.project.telas;


import br.com.project.usuarios.Usuarios;
import br.com.project.usuarios.Clientes;
import br.com.project.usuarios.Login;

import javax.swing.*;

public class TelaLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lblogin = new javax.swing.JLabel();
        Lbsenha = new javax.swing.JLabel();
        CampoSenha = new javax.swing.JPasswordField();
        CampoUsu = new javax.swing.JTextField();
        LbStatusBd = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Lblogin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lblogin.setText("USUÁRIO:");

        Lbsenha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Lbsenha.setText("SENHA:");

        CampoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuActionPerformed(evt);
            }
        });

        LbStatusBd.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/icones/switch-on.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LbStatusBd)
                                                .addGap(113, 113, 113)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Lbsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Lblogin, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CampoUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                                        .addComponent(CampoSenha))))
                                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Lblogin)
                                        .addComponent(CampoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Lbsenha)
                                        .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LbStatusBd))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jButton1)))
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login consul = new Login();

        Object loginResult = consul.Login(CampoUsu, CampoSenha);//todo estudar Object

        //todo  2 coisa  fazer revisar e entender melhore  aprender
        //faz a verificação do retorno se o Object é da classe Admins e essa classe possuo do usuario retornado o "admin" para efetuar o login como admin
        if (loginResult instanceof Usuarios usuarios) {
            // LOGIN ADMIN
            this.dispose();
            String nomeUsuarioLogado = usuarios.getUsuario();
            TelaPrincipal tela = new TelaPrincipal();
            tela.TelaPrincipal2(nomeUsuarioLogado);

            // Habilitar menus para admin
            tela.MenuCadastroCliente.setEnabled(true);
            tela.MenuClientes.setEnabled(true);
            tela.CadastrarAdm.setEnabled(true);
            tela.MenuOS.setEnabled(true);

            tela.setVisible(true);
        //faz a verificação do retorno se o Object é da classe Cliente e essa classe possuo do usuario retornado o "cliente" para efetuar o login como cliente
        } else if (loginResult instanceof Clientes cliente) {
            this.dispose();
            String nomeUsuarioLogado = cliente.getPerfil();
            TelaPrincipal tela = new TelaPrincipal();
            tela.TelaPrincipal2(nomeUsuarioLogado);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Login falhou!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JTextField CampoUsu;
    private javax.swing.JLabel LbStatusBd;
    private javax.swing.JLabel Lblogin;
    private javax.swing.JLabel Lbsenha;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
